import { RepoSnapshot } from "../core/repoAnalyzer";
import { callLLM } from "../core/llmClient";

export interface GeneratedTest {
  file: string;
  target: string;
  framework: string;
  code: string;
}

export async function runTestGeneratorAgent(
  snapshot: RepoSnapshot
): Promise<GeneratedTest[]> {
  const focusedFile =
    snapshot.files.find((f) => f.path.includes("auth")) ?? snapshot.files[0];

  const prompt = `
You are an automated test generation agent.
Target file: ${focusedFile.path}
Language: ${focusedFile.language}

Generate 1-2 high-value unit tests in a popular testing framework.
`;

  const content = await callLLM([
    {
      role: "system",
      content: "You are an expert QA engineer and test architect.",
    },
    { role: "user", content: prompt },
  ]);

  try {
    return JSON.parse(content) as GeneratedTest[];
  } catch {
    // Fallback: always return at least one working Jest test
    return [
      {
        file: "__tests__/auth.spec.ts",
        target: "loginUser",
        framework: "Jest",
        code: `// Auto-generated by AURA (mock)
import { loginUser } from "../src/api/auth";

describe("loginUser", () => {
  it("returns error for missing credentials", () => {
    // This is just illustrative; adapt to real logic.
    const result = loginUser({ username: "", password: "" } as any);
    expect(result).toBeDefined();
  });
});`,
      },
    ];
  }
}
